# Generated by Django 3.2.11 on 2022-01-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=250)),
                ('itemcode', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
